version: '3.8'
services:
  movies:
    image: deveopsmani007/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: devopsmani007/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: devopsmani007/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: devopsmani007/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
