version: '3.8'
services:
  movies:
    image: devopsmani007/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: devopsmani007/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
